CREATE DATABASE IF NOT EXISTS CASPR_database_backup;
USE CASPR_database_backup;

CREATE TABLE Person (
	PersonID INT NOT NULL auto_increment
	, ID_NUM BLOB(5000) NOT NULL
	, ImagePath NVARCHAR(255) NOT NULL
	, Banned BIT NOT NULL DEFAULT 0
	, CreatedAt DateTime NOT NULL
	, FirstName NVARCHAR(255) NOT NULL
	, LastName NVARCHAR(255) NOT NULL
	, PRIMARY KEY (PersonID)
);

CREATE TRIGGER Person_BEFORE_INSERT BEFORE INSERT ON Person
FOR EACH ROW
	SET NEW.CreatedAt = NOW();

CREATE TABLE Log (
	LogID INT NOT NULL auto_increment
	, PersonID INT NOT NULL
	, ImageGUID NVARCHAR(255) NOT NULL
	, LoggedAt DateTime NOT NULL

	, PRIMARY KEY (LogID)
	, FOREIGN KEY (PersonID) REFERENCES Person(PersonID)
);

CREATE TRIGGER Log_BEFORE_INSERT BEFORE INSERT ON Log
FOR EACH ROW
	SET NEW.LoggedAt = NOW();